\i constraints/cart.sql
\i constraints/create_constraints.sql
\i constraints/deposits.sql
\i constraints/gaps.sql
\i constraints/holdings.sql
\i constraints/indicators.sql
\i constraints/pf_summary.sql
\i constraints/portfolios.sql
\i constraints/queries.sql
\i constraints/quotes.sql
\i constraints/sector_quotes.sql
\i constraints/sectors.sql
\i constraints/stock_sector.sql
\i constraints/stocks.sql
\i constraints/trades.sql
\i constraints/watch.sql
