\i tables/cart.sql
\i tables/create_tables.sql
\i tables/deposits.sql
\i tables/exchange.sql
\i tables/gains.sql
\i tables/gaps.sql
\i tables/holdings.sql
\i tables/indicators.sql
\i tables/moving_averages.sql
\i tables/pf_summary.sql
\i tables/portfolios.sql
\i tables/queries.sql
\i tables/quotes.sql
\i tables/sector_quotes.sql
\i tables/sectors.sql
\i tables/standard_deviations_from_mean.sql
\i tables/stock_sector.sql
\i tables/stocks.sql
\i tables/trade_dates.sql
\i tables/trades.sql
\i tables/users.sql
\i tables/watch.sql
